//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyLocation
    {
        public long ID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsVertual { get; set; }
        public Nullable<int> VertualLocationID { get; set; }
        public Nullable<int> LocationTypeID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<long> StateID { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> AreaUnitID { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string Remarks { get; set; }
    }
}
