//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStock
    {
        public long ID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<decimal> OpeningStock { get; set; }
        public Nullable<decimal> ReeceivedStock { get; set; }
        public Nullable<decimal> IssuedStock { get; set; }
        public Nullable<decimal> ClosingStock { get; set; }
        public Nullable<long> FinancialYearID { get; set; }
    
        public virtual FinancialYear FinancialYear { get; set; }
        public virtual ItemMaster ItemMaster { get; set; }
    }
}
