//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemMaster()
        {
            this.ItemStocks = new HashSet<ItemStock>();
            this.ItemStockDetails = new HashSet<ItemStockDetail>();
        }
    
        public long ID { get; set; }
        public long CompanyID { get; set; }
        public long ItemGroupID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string BrandName { get; set; }
        public string ModelNo { get; set; }
        public string Manufacturer { get; set; }
        public string Specification { get; set; }
        public Nullable<short> IsExpired { get; set; }
        public Nullable<long> ItemHSN { get; set; }
        public Nullable<long> PurchaseUnitID { get; set; }
        public Nullable<long> StockUnitID { get; set; }
        public Nullable<long> ProductionUnitID { get; set; }
        public Nullable<long> SalesUnitID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> MinOrderQty { get; set; }
        public Nullable<decimal> MaxStockLevel { get; set; }
        public Nullable<decimal> MinStockLevel { get; set; }
        public Nullable<decimal> SafetyStockLevel { get; set; }
        public Nullable<decimal> MinLotSize { get; set; }
        public Nullable<decimal> MaxLotSize { get; set; }
        public Nullable<long> DimensionUnitID { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<long> WeightUnitID { get; set; }
        public Nullable<decimal> Weight { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ItemGroup ItemGroup { get; set; }
        public virtual ItemHSN ItemHSN1 { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
        public virtual Unit Unit2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemStock> ItemStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemStockDetail> ItemStockDetails { get; set; }
    }
}
