//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemImage
    {
        public long ID { get; set; }
        public Nullable<long> ItemID { get; set; }
        public Nullable<int> ImageType { get; set; }
        public string ImagePath { get; set; }
    }
}
