//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public long ID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<short> MenuType { get; set; }
        public string Title { get; set; }
        public string DefaultURL { get; set; }
        public string Action { get; set; }
        public string Icon { get; set; }
        public string Tooltips { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<long> ParentID { get; set; }
        public bool IsActive { get; set; }
    }
}
