//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMaster.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryControlEntities : DbContext
    {
        public InventoryControlEntities()
            : base("name=InventoryControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyBank> CompanyBanks { get; set; }
        public virtual DbSet<CompanyLocation> CompanyLocations { get; set; }
        public virtual DbSet<CompanyTerm> CompanyTerms { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DocumentsDetail> DocumentsDetails { get; set; }
        public virtual DbSet<DocumentsList> DocumentsLists { get; set; }
        public virtual DbSet<FinancialYear> FinancialYears { get; set; }
        public virtual DbSet<ItemGroup> ItemGroups { get; set; }
        public virtual DbSet<ItemHSN> ItemHSNs { get; set; }
        public virtual DbSet<ItemImage> ItemImages { get; set; }
        public virtual DbSet<ItemMaster> ItemMasters { get; set; }
        public virtual DbSet<ItemStock> ItemStocks { get; set; }
        public virtual DbSet<ItemStockDetail> ItemStockDetails { get; set; }
        public virtual DbSet<LookupData> LookupDatas { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<PartyAddress> PartyAddresses { get; set; }
        public virtual DbSet<PartyContact> PartyContacts { get; set; }
        public virtual DbSet<PartyLedger> PartyLedgers { get; set; }
        public virtual DbSet<PartyLedgerDetail> PartyLedgerDetails { get; set; }
        public virtual DbSet<PartyVehicle> PartyVehicles { get; set; }
        public virtual DbSet<PaymentReceiptDetail> PaymentReceiptDetails { get; set; }
        public virtual DbSet<PaymentReceiptMaster> PaymentReceiptMasters { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UnitConversion> UnitConversions { get; set; }
    }
}
