//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyContact
    {
        public long ID { get; set; }
        public long PartyID { get; set; }
        public string PersonName { get; set; }
        public Nullable<long> Designation { get; set; }
        public Nullable<long> Department { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Phone1 { get; set; }
        public string Mobile { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
