//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyVehicle
    {
        public long ID { get; set; }
        public long PartyID { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleModel { get; set; }
        public Nullable<long> VehicleManufacturer { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
