//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyLedgerDetail
    {
        public long ID { get; set; }
        public long PartyID { get; set; }
        public Nullable<long> FinancialYearID { get; set; }
        public Nullable<long> DocumentID { get; set; }
        public Nullable<long> TransactionID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<short> CRDB { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
