//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyLedger
    {
        public long ID { get; set; }
        public Nullable<long> PartyID { get; set; }
        public Nullable<short> OPCRDR { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<short> CLCRDR { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<long> FinancialYearID { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
