//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Party()
        {
            this.PartyAddresses = new HashSet<PartyAddress>();
            this.PartyContacts = new HashSet<PartyContact>();
            this.PartyLedgers = new HashSet<PartyLedger>();
            this.PartyLedgerDetails = new HashSet<PartyLedgerDetail>();
            this.PartyVehicles = new HashSet<PartyVehicle>();
            this.PaymentReceiptMasters = new HashSet<PaymentReceiptMaster>();
        }
    
        public long ID { get; set; }
        public long CompanyID { get; set; }
        public long PartyType { get; set; }
        public long FirmType { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<long> State { get; set; }
        public Nullable<long> Country { get; set; }
        public string PinCode { get; set; }
        public Nullable<short> RegistrationType { get; set; }
        public string GSTIN { get; set; }
        public Nullable<System.DateTime> GSTINExpDate { get; set; }
        public string TAN { get; set; }
        public Nullable<System.DateTime> TANExpDate { get; set; }
        public string PAN { get; set; }
        public Nullable<System.DateTime> PANExpDate { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<System.DateTime> RegistrationExpDate { get; set; }
        public string MfgLicenceNo { get; set; }
        public Nullable<System.DateTime> MfgLicenceExpDate { get; set; }
        public string DrugLicenceNo { get; set; }
        public string DrugLicenceExpDate { get; set; }
        public string FoodLicenceNo { get; set; }
        public Nullable<System.DateTime> FoodLicenceExpDate { get; set; }
        public Nullable<short> CRDR { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyAddress> PartyAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyContact> PartyContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyLedger> PartyLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyLedgerDetail> PartyLedgerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyVehicle> PartyVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentReceiptMaster> PaymentReceiptMasters { get; set; }
    }
}
