//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyAddress
    {
        public long ID { get; set; }
        public long PartyID { get; set; }
        public long AddressType { get; set; }
        public string Address { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> StateID { get; set; }
        public Nullable<long> CityID { get; set; }
        public string PinCode { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
