//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReceiptDetail
    {
        public long ID { get; set; }
        public long CompanyID { get; set; }
        public long DocumentID { get; set; }
        public Nullable<long> PaymentReceiptMasterID { get; set; }
        public Nullable<long> TransactionMasterID { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<long> PayModeID { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<long> CompanyBankID { get; set; }
        public Nullable<long> PartyBankName { get; set; }
        public string PartyBankBranch { get; set; }
        public string PartyBankIFSC { get; set; }
        public string PartyBankMICR { get; set; }
        public string InstrumentNo { get; set; }
        public Nullable<long> PartyBankAccountType { get; set; }
        public Nullable<System.DateTime> InstrumentDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Company Company { get; set; }
        public virtual PaymentReceiptMaster PaymentReceiptMaster { get; set; }
    }
}
