//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitConversion
    {
        public long ID { get; set; }
        public long CompanyID { get; set; }
        public string Name { get; set; }
        public Nullable<long> FromUnitID { get; set; }
        public Nullable<int> FromValue { get; set; }
        public Nullable<long> ToUnitID { get; set; }
        public Nullable<int> ToValue { get; set; }
        public string Ratio { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
